### ISSUE TITLE
Using with Dependency fail

### ISSUE THREAD

**Issue by Gerych1984** [yiisoft/cache-db#6]
Good day. I have next case:

1. Some external paid API with limited requests per time
2. The parts of the methods from this API free for use (like version, data-version, balance etc)
3. I cached paid results from this API using cache-db (to be independent from reboot of production machine). It's ok
4. Today i start using `TagDependency` with **tag** equals $api->dataVersion() and i have fail with $value['data'] is **resource** instead of **string** and it cannot be unserialized. But it's still works without dependency

DB - PostgreSql 14 with bytea data type

**Comment by terabytesoftw** [comment]
> Good day. I have next case:
> 
> 1. Some external paid API with limited requests per time
> 2. The parts of the methods from this API free for use (like version, data-version, balance etc)
> 3. I cached paid results from this API using cache-db (to be independent from reboot of production machine). It's ok
> 4. Today i start using `TagDependency` with **tag** equals $api->dataVersion() and i have fail with $value['data'] is **resource** instead of **string** and it cannot be unserialized. But it's still works without dependency
> 
> DB - PostgreSql 14 with bytea data type

Please could you write the code that fails to reproduce the problem,
